# Generated by Django 3.2.6 on 2022-01-13 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_system', '0002_accessoryproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessoryproxy',
            options={'verbose_name': 'Accessory', 'verbose_name_plural': 'Accessories'},
        ),
    ]
