# Generated by Django 3.2.6 on 2022-01-14 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_auto_20220114_1234'),
        ('customers', '0003_auto_20220114_1234'),
        ('properties', '0014_auto_20220114_1234'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks_system', '0009_historicalcomment_historicaltask_historicaltaskclosed_historicaltaskopen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcomment',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'History'},
        ),
        migrations.AlterModelOptions(
            name='historicaltask',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'History'},
        ),
        migrations.AlterModelOptions(
            name='historicaltaskclosed',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'History'},
        ),
        migrations.AlterModelOptions(
            name='historicaltaskopen',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'History'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='modified',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='deadline',
            field=models.DateField(verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='device_name',
            field=models.CharField(max_length=250, verbose_name='Device name'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='device_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='properties.category', verbose_name='Device type'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Estimated price'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='fault_description',
            field=models.TextField(verbose_name='Fault description'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='modified',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='priority',
            field=models.IntegerField(choices=[(4, 'Low'), (3, 'Normal'), (2, 'Important'), (1, 'Critical')], default=3, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='registrant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Registrant'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='repair_description',
            field=models.TextField(blank=True, null=True, verbose_name='Repair description'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='send_notification',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'E-mail'), ('no', "Don't notify")], default='no', max_length=5, verbose_name='Send notification'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('close', 'Closed')], default='open', max_length=5, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='technician',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Technician'),
        ),
        migrations.AlterField(
            model_name='historicaltaskclosed',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='historicaltaskclosed',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='historicaltaskclosed',
            name='deadline',
            field=models.DateField(verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='historicaltaskclosed',
            name='device_name',
            field=models.CharField(max_length=250, verbose_name='Device name'),
        ),
        migrations.AlterField(
            model_name='historicaltaskclosed',
            name='device_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='properties.category', verbose_name='Device type'),
        ),
        migrations.AlterField(
            model_name='historicaltaskclosed',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Estimated price'),
        ),
        migrations.AlterField(
            model_name='historicaltaskclosed',
            name='fault_description',
            field=models.TextField(verbose_name='Fault description'),
        ),
        migrations.AlterField(
            model_name='historicaltaskclosed',
            name='modified',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='historicaltaskclosed',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='historicaltaskclosed',
            name='priority',
            field=models.IntegerField(choices=[(4, 'Low'), (3, 'Normal'), (2, 'Important'), (1, 'Critical')], default=3, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='historicaltaskclosed',
            name='registrant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Registrant'),
        ),
        migrations.AlterField(
            model_name='historicaltaskclosed',
            name='repair_description',
            field=models.TextField(blank=True, null=True, verbose_name='Repair description'),
        ),
        migrations.AlterField(
            model_name='historicaltaskclosed',
            name='send_notification',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'E-mail'), ('no', "Don't notify")], default='no', max_length=5, verbose_name='Send notification'),
        ),
        migrations.AlterField(
            model_name='historicaltaskclosed',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('close', 'Closed')], default='open', max_length=5, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicaltaskclosed',
            name='technician',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Technician'),
        ),
        migrations.AlterField(
            model_name='historicaltaskopen',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='historicaltaskopen',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='historicaltaskopen',
            name='deadline',
            field=models.DateField(verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='historicaltaskopen',
            name='device_name',
            field=models.CharField(max_length=250, verbose_name='Device name'),
        ),
        migrations.AlterField(
            model_name='historicaltaskopen',
            name='device_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='properties.category', verbose_name='Device type'),
        ),
        migrations.AlterField(
            model_name='historicaltaskopen',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Estimated price'),
        ),
        migrations.AlterField(
            model_name='historicaltaskopen',
            name='fault_description',
            field=models.TextField(verbose_name='Fault description'),
        ),
        migrations.AlterField(
            model_name='historicaltaskopen',
            name='modified',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='historicaltaskopen',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='historicaltaskopen',
            name='priority',
            field=models.IntegerField(choices=[(4, 'Low'), (3, 'Normal'), (2, 'Important'), (1, 'Critical')], default=3, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='historicaltaskopen',
            name='registrant',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Registrant'),
        ),
        migrations.AlterField(
            model_name='historicaltaskopen',
            name='repair_description',
            field=models.TextField(blank=True, null=True, verbose_name='Repair description'),
        ),
        migrations.AlterField(
            model_name='historicaltaskopen',
            name='send_notification',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'E-mail'), ('no', "Don't notify")], default='no', max_length=5, verbose_name='Send notification'),
        ),
        migrations.AlterField(
            model_name='historicaltaskopen',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('close', 'Closed')], default='open', max_length=5, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicaltaskopen',
            name='technician',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Technician'),
        ),
        migrations.AlterField(
            model_name='task',
            name='accessories',
            field=models.ManyToManyField(related_name='tasks', to='devices.Accessory', verbose_name='Accessories'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='task',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='customers.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='task',
            name='device_name',
            field=models.CharField(max_length=250, verbose_name='Device name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='properties.category', verbose_name='Device type'),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Estimated price'),
        ),
        migrations.AlterField(
            model_name='task',
            name='fault_description',
            field=models.TextField(verbose_name='Fault description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='task',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(4, 'Low'), (3, 'Normal'), (2, 'Important'), (1, 'Critical')], default=3, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='task',
            name='registrant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Registrant'),
        ),
        migrations.AlterField(
            model_name='task',
            name='repair_description',
            field=models.TextField(blank=True, null=True, verbose_name='Repair description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='send_notification',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'E-mail'), ('no', "Don't notify")], default='no', max_length=5, verbose_name='Send notification'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('close', 'Closed')], default='open', max_length=5, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Technician'),
        ),
    ]
