# Generated by Django 3.2.6 on 2021-11-17 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_alter_config_data'),
        ('price_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('properties.category',),
        ),
        migrations.CreateModel(
            name='ShopProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('properties.shop',),
        ),
    ]
