# Generated by Django 3.2.6 on 2022-01-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_historicalcustomer_historicalcustomerproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='historicalcustomer',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'History'},
        ),
        migrations.AlterModelOptions(
            name='historicalcustomerproxy',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'History'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=40, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=60, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=9, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='first_name',
            field=models.CharField(max_length=40, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='last_name',
            field=models.CharField(max_length=60, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='modified',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='phone_number',
            field=models.CharField(max_length=9, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='historicalcustomerproxy',
            name='created',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='historicalcustomerproxy',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='historicalcustomerproxy',
            name='first_name',
            field=models.CharField(max_length=40, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='historicalcustomerproxy',
            name='last_name',
            field=models.CharField(max_length=60, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='historicalcustomerproxy',
            name='modified',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='historicalcustomerproxy',
            name='phone_number',
            field=models.CharField(max_length=9, verbose_name='Phone number'),
        ),
    ]
