# Generated by Django 3.2.6 on 2021-11-05 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=12)),
                ('manufacturer_code', models.CharField(max_length=255)),
                ('shop_code', models.CharField(max_length=255)),
                ('availability', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LaptopSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.IntegerField()),
                ('processor', models.CharField(max_length=1025)),
                ('graphic_card', models.CharField(max_length=255)),
                ('drive_capacity', models.IntegerField()),
                ('drive_type', models.CharField(max_length=3)),
                ('screen_size', models.DecimalField(decimal_places=1, max_digits=2)),
                ('screen_resolution', models.CharField(max_length=25)),
                ('system', models.BooleanField(default=False)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.laptop')),
            ],
        ),
    ]
