# Generated by Django 3.2.6 on 2021-11-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='model',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
