# Generated by Django 3.2.6 on 2021-11-05 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_laptop_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='type',
            field=models.CharField(choices=[('ALTCOMP', 'Altcomp'), ('OTHER', 'Other')], default='OTHER', max_length=8),
        ),
    ]
