# Generated by Django 3.2.6 on 2021-11-05 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_laptop_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='type',
        ),
        migrations.AddField(
            model_name='laptop',
            name='external_link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='internal_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
