# Generated by Django 3.2.6 on 2021-11-06 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_auto_20211105_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='internal_link',
        ),
    ]
