# Generated by Django 3.2.6 on 2021-11-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_price_created'),
        ('devices', '0008_laptop_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='category',
        ),
        migrations.AddField(
            model_name='laptop',
            name='category',
            field=models.ManyToManyField(blank=True, to='properties.Category'),
        ),
    ]
