# Generated by Django 3.2.6 on 2021-11-10 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_alter_config_data'),
        ('devices', '0009_auto_20211106_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.shop'),
        ),
    ]
