# Generated by Django 3.2.6 on 2022-01-14 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_auto_20220114_1234'),
        ('devices', '0011_accessory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessory',
            options={'verbose_name': 'Accessory', 'verbose_name_plural': 'Accessories'},
        ),
        migrations.AlterModelOptions(
            name='laptop',
            options={'verbose_name': 'Laptop', 'verbose_name_plural': 'Laptops'},
        ),
        migrations.AlterModelOptions(
            name='laptopspecification',
            options={'verbose_name': 'Laptop specification', 'verbose_name_plural': 'Laptops specifications'},
        ),
        migrations.AlterField(
            model_name='accessory',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='availability',
            field=models.BooleanField(default=True, verbose_name='Availability'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='brand',
            field=models.CharField(blank=True, max_length=12, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='category',
            field=models.ManyToManyField(blank=True, to='properties.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='external_link',
            field=models.URLField(verbose_name='External link'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='manufacturer_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Manufacturer code'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='model',
            field=models.CharField(blank=True, max_length=255, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.shop', verbose_name='Shop'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='shop_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='Shop code'),
        ),
        migrations.AlterField(
            model_name='laptopspecification',
            name='drive_capacity',
            field=models.IntegerField(blank=True, verbose_name='Drive capacity'),
        ),
        migrations.AlterField(
            model_name='laptopspecification',
            name='drive_type',
            field=models.CharField(blank=True, max_length=3, verbose_name='Drive type'),
        ),
        migrations.AlterField(
            model_name='laptopspecification',
            name='graphic_card',
            field=models.CharField(blank=True, max_length=255, verbose_name='Graphic Card'),
        ),
        migrations.AlterField(
            model_name='laptopspecification',
            name='laptop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.laptop', verbose_name='Laptop'),
        ),
        migrations.AlterField(
            model_name='laptopspecification',
            name='memory',
            field=models.IntegerField(blank=True, verbose_name='Memory'),
        ),
        migrations.AlterField(
            model_name='laptopspecification',
            name='processor',
            field=models.CharField(blank=True, max_length=1025, verbose_name='Processor'),
        ),
        migrations.AlterField(
            model_name='laptopspecification',
            name='screen_resolution',
            field=models.CharField(blank=True, max_length=25, verbose_name='Screen resolution'),
        ),
        migrations.AlterField(
            model_name='laptopspecification',
            name='screen_size',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, verbose_name='Screen size'),
        ),
        migrations.AlterField(
            model_name='laptopspecification',
            name='system',
            field=models.BooleanField(default=False, verbose_name='System'),
        ),
    ]
