# Generated by Django 3.2.6 on 2021-11-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_price_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
