# Generated by Django 3.2.6 on 2021-11-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20211106_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalsales',
            name='all_items',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='internalsales',
            name='available_items',
            field=models.IntegerField(blank=True),
        ),
    ]
