# Generated by Django 3.2.6 on 2021-11-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_auto_20211106_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
