# Generated by Django 3.2.6 on 2021-11-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_alter_internalsales_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalsales',
            name='margin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
