# Generated by Django 3.2.6 on 2021-11-10 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_alter_internalsales_margin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='properties.shop')),
            ],
        ),
    ]
