# Generated by Django 3.2.6 on 2021-11-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='data',
            field=models.JSONField(default={}),
        ),
    ]
