# Generated by Django 3.2.6 on 2021-11-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_alter_config_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='data',
            field=models.JSONField(default={'availability': [], 'brand': [], 'manufacturer_code': [], 'price': [], 'shop_code': []}),
        ),
    ]
