# Generated by Django 3.2.6 on 2022-01-14 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_alter_config_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name': 'Config', 'verbose_name_plural': 'Configs'},
        ),
        migrations.AlterModelOptions(
            name='internalsales',
            options={'verbose_name': 'Internal sales', 'verbose_name_plural': 'Internal sales'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Price', 'verbose_name_plural': 'Prizes'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Shop', 'verbose_name_plural': 'Shops'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='config',
            name='data',
            field=models.JSONField(default={'availability': [], 'brand': [], 'manufacturer_code': [], 'price': [], 'shop_code': []}, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='config',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='properties.shop', verbose_name='Shop'),
        ),
        migrations.AlterField(
            model_name='internalsales',
            name='all_items',
            field=models.IntegerField(blank=True, verbose_name='All items'),
        ),
        migrations.AlterField(
            model_name='internalsales',
            name='available_items',
            field=models.IntegerField(blank=True, verbose_name='Avaliable items'),
        ),
        migrations.AlterField(
            model_name='internalsales',
            name='internal_link',
            field=models.URLField(blank=True, null=True, verbose_name='Internal link'),
        ),
        migrations.AlterField(
            model_name='internalsales',
            name='margin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Margin'),
        ),
        migrations.AlterField(
            model_name='price',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='price',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='price',
            name='type',
            field=models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], default='EXTERNAL', max_length=8, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='price',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
