# Generated by Django 3.2.6 on 2021-11-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('viewed', models.BooleanField(default=False)),
                ('changes', models.JSONField(default={})),
                ('link', models.URLField()),
            ],
        ),
    ]
