# Generated by Django 3.2.6 on 2021-11-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='changes',
            field=models.JSONField(default=dict),
        ),
    ]
