# Generated by Django 3.2.6 on 2022-01-14 11:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20211117_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='notificationconfig',
            options={'verbose_name': 'Notification Config', 'verbose_name_plural': 'Notifications Config'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='changes',
            field=models.JSONField(default=dict, verbose_name='Changes'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.URLField(verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='viewed',
            field=models.BooleanField(default=False, verbose_name='Viewed'),
        ),
        migrations.AlterField(
            model_name='notificationconfig',
            name='emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, null=True, size=None, verbose_name='Emails'),
        ),
        migrations.AlterField(
            model_name='notificationconfig',
            name='refresh_interval',
            field=models.IntegerField(default=1, verbose_name='Refresh interval'),
        ),
        migrations.AlterField(
            model_name='notificationconfig',
            name='send_mail',
            field=models.BooleanField(default=False, verbose_name='Send E-mail'),
        ),
    ]
