# Generated by Django 3.2.6 on 2021-11-17 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationConfig',
        ),
    ]
