# Generated by Django 3.2.6 on 2021-11-17 17:19

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0006_notificationconfig'),
        ('settings', '0002_delete_notificationconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfigProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Notification config',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('notifications.notificationconfig',),
        ),
    ]
