# Generated by Django 3.2.6 on 2021-11-17 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20211117_2023'),
        ('settings', '0003_notificationconfigproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('notifications.notification',),
        ),
        migrations.AlterModelOptions(
            name='notificationconfigproxy',
            options={'verbose_name': 'Notification config', 'verbose_name_plural': 'Notifications config'},
        ),
    ]
