# Generated by Django 3.2.6 on 2022-01-14 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_userproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationconfigproxy',
            options={'verbose_name': 'Notification Config', 'verbose_name_plural': 'Notifications Config'},
        ),
    ]
